### ISSUE TITLE
[get-it] 해커톤 앱 제출

### ISSUE THREAD

**Issue by mini-777** [hackersground-kr/hackers-ground-2023#109]
**👆👆👆 상단의 제목에 팀 이름을 반드시 적어 주세요 👆👆👆**

- **팀 이름**: get-it
- **팀 리포지토리**: https://github.com/hackersground-kr/Get-It

**Comment by justinyoo** [comment]
팀이름 대소문자 확인 과정에서 문제가 발생했습니다. 현재 시스템에서 확인 가능하므로 @kkyh12180 진행해 주세요

**Comment by kkyh12180** [comment]
@mini-777 5번 github actions workflow 과정에서 에러가 발생합니다.

![image](https://github.com/hackersground-kr/hackers-ground/assets/80297525/e5092a36-414a-47db-9033-3cbde8859736)

**Comment by kkyh12180** [comment]
![image](https://github.com/hackersground-kr/hackers-ground/assets/80297525/c49dbada-afc6-4d06-aa46-5c75f5ccb7aa)

**Comment by pmh-only** [comment]
명령어 수정했습니다
`azd auth login` 전 `az login`이 필요합니다.

**Comment by kkyh12180** [comment]
@mini-777 round4 제출 부탁드립니다!

**Comment by kkyh12180** [comment]
@mini-777 아 round4가 아니라 추후 공지 확인하시고 맞게 제출해주세요!
