### ISSUE TITLE
[Travling] 해커톤 앱 제출

### ISSUE THREAD

**Issue by yeseong0412** [hackersground-kr/hackers-ground-2023#113]
**👆👆👆 상단의 제목에 팀 이름을 반드시 적어 주세요 👆👆👆**

- **팀 이름**: Travling
- **팀 리포지토리**: https://github.com/hackersground-kr/Travling

**Comment by JunHyungJang** [comment]
마지막줄에 "다운로드한 파일을 안드로이드 폰에서 실행하여 설치한다. "라고 적혀있는데 혹시 emulator로 실행시키는 방법도 있나요 ??

**Comment by JunHyungJang** [comment]
step by step 에서 "알맞는 리소스 그룹을 선택해요 (만들어요)" 이 문장이 이해가 안가는데 좀 더 구체적으로 설명해주실수 있을까요 ?? 직접 오는게 편하시면 기술 검증단 쪽으로  오셔서 '장준형' 학생을 찾아주세요 !!

**Comment by JunHyungJang** [comment]
8:38:51 PM: Error: The web site helperr cannot be found.
8:39:03 PM: Error: The Resource 'Microsoft.Web/sites/pyl-webapp' under resource group 'rg-hg-httpsgithubcomhackersground-krazure-kawaii' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix
8:40:17 PM test-travling-app: Starting deployment...
8:40:28 PM test-travling-app: Creating zip package...
8:40:28 PM test-travling-app: Ignoring files from "appService.zipIgnorePattern"
"node_modules{,/**}"
".vscode{,/**}"
8:40:28 PM test-travling-app: Zip package size: 7.89 kB
8:40:33 PM test-travling-app: Updating submodules.
8:40:34 PM test-travling-app: Preparing deployment for commit id 'c966ba25-9'.
8:40:34 PM test-travling-app: PreDeployment: context.CleanOutputPath False
8:40:34 PM test-travling-app: PreDeployment: context.OutputPath /home/site/wwwroot
8:40:35 PM test-travling-app: Repository path is /tmp/zipdeploy/extracted
8:40:35 PM test-travling-app: Running oryx build...
8:40:35 PM test-travling-app: Command: oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform nodejs --platform-version 18 -p virtualenv_name= --log-file /tmp/build-debug.log  -i /tmp/8db73157dedd490 -p compress_node_modules=tar-gz | tee /tmp/oryx-build.log
8:40:35 PM test-travling-app: Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
8:40:35 PM test-travling-app: You can report issues at https://github.com/Microsoft/Oryx/issues
8:40:35 PM test-travling-app: Oryx Version: 0.2.20230508.1, Commit: 7fe2bf39b357dd68572b438a85ca50b5ecfb4592, ReleaseTagName: 20230508.1
8:40:35 PM test-travling-app: Build Operation ID: 632f8a4003d2cec7
8:40:35 PM test-travling-app: Repository Commit : c966ba25-93d7-45e4-8c41-b03544518a77
8:40:35 PM test-travling-app: OS Type           : bullseye
8:40:35 PM test-travling-app: Image Type        : githubactions
8:40:35 PM test-travling-app: Detecting platforms...
8:40:35 PM test-travling-app: Could not detect any platform in the source directory.
8:40:35 PM test-travling-app: Error: Couldn't detect a version for the platform 'nodejs' in the repo.
8:40:36 PM test-travling-app: /bin/bash -c "oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform nodejs --platform-version 18 -p virtualenv_name= --log-file /tmp/build-debug.log  -i /tmp/8db73157dedd490 -p compress_node_modules=tar-gz | tee /tmp/oryx-build.log ; exit $PIPESTATUS "
8:40:37 PM test-travling-app: Generating summary of Oryx build
8:40:37 PM test-travling-app: Parsing the build logs
8:40:37 PM test-travling-app: Found 0 issue(s)
8:40:37 PM test-travling-app: Build Summary :
8:40:37 PM test-travling-app: ===============
8:40:37 PM test-travling-app: Errors (0)
8:40:37 PM test-travling-app: Warnings (0)
8:40:38 PM test-travling-app: Deployment Failed. deployer = ms-azuretools-vscode deploymentPath = ZipDeploy. Extract zip.
8:40:44 PM test-travling-app: Deployment failed.
8:42:30 PM test-travling-app: Starting deployment...
8:42:30 PM test-travling-app: Creating zip package...
8:42:30 PM test-travling-app: Ignoring files from "appService.zipIgnorePattern"
"node_modules{,/**}"
".vscode{,/**}"
8:42:31 PM test-travling-app: Zip package size: 7.89 kB
8:42:31 PM test-travling-app: Fetching changes.
8:42:32 PM test-travling-app: Cleaning up temp folders from previous zip deployments and extracting pushed zip file /tmp/zipdeploy/2d9d406a-6861-4b6b-be13-b6d63d3968f4.zip (0.01 MB) to /tmp/zipdeploy/extracted
8:42:34 PM test-travling-app: Updating submodules.
8:42:35 PM test-travling-app: Preparing deployment for commit id '9246aa6c-b'.
8:42:36 PM test-travling-app: PreDeployment: context.CleanOutputPath False
8:42:36 PM test-travling-app: PreDeployment: context.OutputPath /home/site/wwwroot
8:42:36 PM test-travling-app: Repository path is /tmp/zipdeploy/extracted
8:42:36 PM test-travling-app: Running oryx build...
8:42:36 PM test-travling-app: Command: oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform nodejs --platform-version 18 -p virtualenv_name= --log-file /tmp/build-debug.log  -i /tmp/8db7315c632285a -p compress_node_modules=tar-gz | tee /tmp/oryx-build.log
8:42:36 PM test-travling-app: Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
8:42:36 PM test-travling-app: You can report issues at https://github.com/Microsoft/Oryx/issues
8:42:36 PM test-travling-app: Oryx Version: 0.2.20230508.1, Commit: 7fe2bf39b357dd68572b438a85ca50b5ecfb4592, ReleaseTagName: 20230508.1
8:42:36 PM test-travling-app: Build Operation ID: 49c7236409147f78
8:42:36 PM test-travling-app: Repository Commit : 9246aa6c-ba5f-4c06-88f8-eeef0b631bbd
8:42:36 PM test-travling-app: Error: Couldn't detect a version for the platform 'nodejs' in the repo.
8:42:37 PM test-travling-app: OS Type           : bullseye
8:42:37 PM test-travling-app: Image Type        : githubactions
8:42:37 PM test-travling-app: Detecting platforms...
8:42:37 PM test-travling-app: Could not detect any platform in the source directory.
8:42:37 PM test-travling-app: /bin/bash -c "oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform nodejs --platform-version 18 -p virtualenv_name= --log-file /tmp/build-debug.log  -i /tmp/8db7315c632285a -p compress_node_modules=tar-gz | tee /tmp/oryx-build.log ; exit $PIPESTATUS "
8:42:38 PM test-travling-app: Generating summary of Oryx build
8:42:38 PM test-travling-app: Parsing the build logs
8:42:38 PM test-travling-app: Found 0 issue(s)
8:42:38 PM test-travling-app: Build Summary :
8:42:38 PM test-travling-app: ===============
8:42:38 PM test-travling-app: Errors (0)
8:42:38 PM test-travling-app: Warnings (0)
8:42:39 PM test-travling-app: Deployment Failed. deployer = ms-azuretools-vscode deploymentPath = ZipDeploy. Extract zip.
8:42:45 PM test-travling-app: Deployment failed.
8:43:31 PM test-travling-app: Starting deployment...
8:43:31 PM test-travling-app: Creating zip package...
8:43:31 PM test-travling-app: Ignoring files from "appService.zipIgnorePattern"
"node_modules{,/**}"
".vscode{,/**}"
8:43:31 PM test-travling-app: Zip package size: 7.89 kB
8:43:35 PM test-travling-app: Updating submodules.
8:43:36 PM test-travling-app: Preparing deployment for commit id 'effbf062-7'.
8:43:36 PM test-travling-app: PreDeployment: context.CleanOutputPath False
8:43:36 PM test-travling-app: PreDeployment: context.OutputPath /home/site/wwwroot
8:43:37 PM test-travling-app: Repository path is /tmp/zipdeploy/extracted
8:43:37 PM test-travling-app: Running oryx build...
8:43:37 PM test-travling-app: Command: oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform nodejs --platform-version 18 -p virtualenv_name= --log-file /tmp/build-debug.log  -i /tmp/8db7315ea684410 -p compress_node_modules=tar-gz | tee /tmp/oryx-build.log
8:43:37 PM test-travling-app: Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
8:43:37 PM test-travling-app: You can report issues at https://github.com/Microsoft/Oryx/issues
8:43:37 PM test-travling-app: Oryx Version: 0.2.20230508.1, Commit: 7fe2bf39b357dd68572b438a85ca50b5ecfb4592, ReleaseTagName: 20230508.1
8:43:37 PM test-travling-app: Error: Couldn't detect a version for the platform 'nodejs' in the repo.
8:43:37 PM test-travling-app: Build Operation ID: f384b8d88e671810
8:43:37 PM test-travling-app: Repository Commit : effbf062-7e79-4220-982d-804246439b4f
8:43:37 PM test-travling-app: OS Type           : bullseye
8:43:37 PM test-travling-app: Image Type        : githubactions
8:43:37 PM test-travling-app: Detecting platforms...
8:43:37 PM test-travling-app: Could not detect any platform in the source directory.
8:43:38 PM test-travling-app: /bin/bash -c "oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform nodejs --platform-version 18 -p virtualenv_name= --log-file /tmp/build-debug.log  -i /tmp/8db7315ea684410 -p compress_node_modules=tar-gz | tee /tmp/oryx-build.log ; exit $PIPESTATUS "
8:43:38 PM test-travling-app: Generating summary of Oryx build
8:43:39 PM test-travling-app: Parsing the build logs
8:43:39 PM test-travling-app: Found 0 issue(s)
8:43:39 PM test-travling-app: Build Summary :
8:43:39 PM test-travling-app: ===============
8:43:39 PM test-travling-app: Errors (0)
8:43:39 PM test-travling-app: Warnings (0)
8:43:40 PM test-travling-app: Deployment Failed. deployer = ms-azuretools-vscode deploymentPath = ZipDeploy. Extract zip.
8:43:44 PM test-travling-app: Deployment failed.

**Comment by JunHyungJang** [comment]
11:11:59 PM test-travling-app2: Starting deployment...
11:12:02 PM test-travling-app2: Creating zip package...
11:12:02 PM test-travling-app2: Ignoring files from "appService.zipIgnorePattern"
"node_modules{,/**}"
".vscode{,/**}"
11:12:02 PM test-travling-app2: Zip package size: 7.79 kB
11:12:07 PM test-travling-app2: Updating submodules.
11:12:08 PM test-travling-app2: Preparing deployment for commit id 'd57981c5-c'.
11:12:08 PM test-travling-app2: PreDeployment: context.CleanOutputPath False
11:12:08 PM test-travling-app2: PreDeployment: context.OutputPath /home/site/wwwroot
11:12:08 PM test-travling-app2: Repository path is /tmp/zipdeploy/extracted
11:12:08 PM test-travling-app2: Running oryx build...
11:12:08 PM test-travling-app2: Command: oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform nodejs --platform-version 18 -p virtualenv_name= --log-file /tmp/build-debug.log  -i /tmp/8db732aaa2b6bec -p compress_node_modules=tar-gz | tee /tmp/oryx-build.log
11:12:09 PM test-travling-app2: Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
11:12:09 PM test-travling-app2: You can report issues at https://github.com/Microsoft/Oryx/issues
11:12:09 PM test-travling-app2: Oryx Version: 0.2.20230508.1, Commit: 7fe2bf39b357dd68572b438a85ca50b5ecfb4592, ReleaseTagName: 20230508.1
11:12:09 PM test-travling-app2: Build Operation ID: 1f83ab79ec4faf3a
11:12:09 PM test-travling-app2: Repository Commit : d57981c5-c7c7-436f-84f5-9ec646c327ec
11:12:09 PM test-travling-app2: OS Type           : bullseye
11:12:09 PM test-travling-app2: Image Type        : githubactions
11:12:09 PM test-travling-app2: Detecting platforms...
11:12:09 PM test-travling-app2: Could not detect any platform in the source directory.
11:12:09 PM test-travling-app2: Error: Couldn't detect a version for the platform 'nodejs' in the repo.
11:12:10 PM test-travling-app2: /bin/bash -c "oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform nodejs --platform-version 18 -p virtualenv_name= --log-file /tmp/build-debug.log  -i /tmp/8db732aaa2b6bec -p compress_node_modules=tar-gz | tee /tmp/oryx-build.log ; exit $PIPESTATUS "
11:12:11 PM test-travling-app2: Generating summary of Oryx build
11:12:11 PM test-travling-app2: Parsing the build logs
11:12:11 PM test-travling-app2: Found 0 issue(s)
11:12:11 PM test-travling-app2: Build Summary :
11:12:11 PM test-travling-app2: ===============
11:12:11 PM test-travling-app2: Errors (0)
11:12:11 PM test-travling-app2: Warnings (0)
11:12:12 PM test-travling-app2: Deployment Failed. deployer = ms-azuretools-vscode deploymentPath = ZipDeploy. Extract zip.
11:12:17 PM test-travling-app2: Deployment failed.

**Comment by JunHyungJang** [comment]
node:internal/fs/utils:344
    throw err;
    ^

Error: ENOENT: no such file or directory, open './DigiCertGlobalRootCA.crt.pem'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at Object.<anonymous> (c:\Users\kevin\Desktop\hackerton\travling\Maru-Backend\Maru-Backend\index.js:15:12)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: './DigiCertGlobalRootCA.crt.pem'
}
