### ISSUE TITLE
[CoBo] 해커톤 앱 제출

### ISSUE THREAD

**Issue by Yeachan-Kim** [hackersground-kr/hackers-ground-2023#114]
**👆👆👆 상단의 제목에 팀 이름을 반드시 적어 주세요 👆👆👆**

- **팀 이름**: CoBo
- **팀 리포지토리**: https://github.com/hackersground-kr/cobo-team

**Comment by tula3and** [comment]
@Yeachan-Kim 안녕하세요, 시작하기에 앱 빌딩에 필요한 지시가 따로 없는데 업데이트 부탁드립니다.

**Comment by tula3and** [comment]
@Yeachan-Kim Fork를 처음 하면 Github Actions가 기본적으로 켜져 있지 않아 5번 설명에 Enable 하는 것이 필요하다고 적어주는 것이 좋을 거 같습니다. 아래에 처음 뜨는 화면을 첨부합니다.

![image](https://github.com/hackersground-kr/hackers-ground/assets/62553200/f6ca8f4e-2eee-40fe-918c-4e1fc6c29138)

**Comment by tula3and** [comment]
@Yeachan-Kim 2번에 리소스 그룹 선택에서, 처음 만드는 사람 입장에서는 리소스 그룹도 없기 때문에 이걸 만드는 과정도 따로 추가가 필요할 듯 싶습니다.

**Comment by tula3and** [comment]
@Yeachan-Kim 2번에 런타임 스택에서, 버전만 적는 것이 아닌 어떤 런타임을 기반으로 하는지 적어주어야 합니다.

**Comment by tula3and** [comment]
@Yeachan-Kim 2번 마지막 문장에서 새로운 workflow를 추가하는 것이 아닌 기존의 workflow를 쓰도록 권장하는 문구로 고쳐야 할 것 같습니다. 그 후 Save 버튼을 누르도록 하는 문구도 필요할 거 같습니다.

![image](https://github.com/hackersground-kr/hackers-ground/assets/62553200/dcb8936c-1d46-451e-bb6b-edc11f722da9)

**Comment by tula3and** [comment]
@Yeachan-Kim 3번에서 Speech Services 검색해도 안 뜹니다. 해당 내용 수정 바랍니다.

![image](https://github.com/hackersground-kr/hackers-ground/assets/62553200/8218324d-8a7c-4c57-b3b4-dbebbbbdffa3)

**Comment by tula3and** [comment]
@Yeachan-Kim [chatGptApi.py](https://github.com/hackersground-kr/cobo-team/blob/main/chatGptApi.py)에서 이렇게 직접적으로 API 키를 노출하도록 유도하면 안 됩니다. 아래 문서 참고하셔서 Github Secret 사용하는 것으로 수정해주세요.

- https://wikidocs.net/81074
- https://medium.datadriveninvestor.com/accessing-github-secrets-in-python-d3e758d8089b

마찬가지로 speechToText.py 파일과 textToSpeech.py 파일도 키를 노출하지 않도록 수정해주세요.

**Comment by tula3and** [comment]
@Yeachan-Kim 배포 실패했는데 여기 Github Actions 실행 결과 https://github.com/tula3and/cobo-test/actions 참고하셔서 수정바랍니다.

![image](https://github.com/hackersground-kr/hackers-ground/assets/62553200/9603082a-6b16-4b8f-b994-b6bc6de233a0)

**Comment by fndl5759** [comment]
[tula3and](https://github.com/tula3and) 수정했습니다. 확인부탁드립니다.

**Comment by tula3and** [comment]
@Yeachan-Kim 리드미대로 했는데 아래의 에러가 떴습니다. 확인 부탁드립니다. 그리고 SPEECH_KEY의 경우 key 1과 key 2의 상관은 없는 건가요?

![image](https://github.com/hackersground-kr/hackers-ground/assets/62553200/e9820f78-0cdc-4b3b-a200-f7787bf50ed9)
