### ISSUE TITLE
[배그] 해커톤 앱 제출

### ISSUE THREAD

**Issue by yongbin1** [hackersground-kr/hackers-ground-2023#120]
**👆👆👆 상단의 제목에 팀 이름을 반드시 적어 주세요 👆👆👆**

- **팀 이름** : 배그
- **팀 리포지토리**: https://github.com/hackersground-kr/smonkey

**Comment by kkyh12180** [comment]
@yongbin1 
1. git clone의 과정을 명시해주세요.
2. 리소스 생성 과정에서 오류가 발생합니다. 
![image](https://github.com/hackersground-kr/hackers-ground/assets/80297525/6c5dcf88-41c3-4a95-8760-c8c62deec427)

**Comment by yongbin1** [comment]
@kkyh12180 
1. git clone이 아니라 깃허브 계정에 포크 받는 것인데 클론 받는 것으로 바꾸어야하나요??
2. 리소스 생성이 이미 되어있어 생성이 되지 않은 오류라 기존 리소스를 삭제하여 오류 해결했습니다!!

**Comment by kkyh12180** [comment]
@yongbin1 
1. 죄송합니다. 착각했습니다.
2. 확인했습니다. 계속 진행하고 문제 생기면 다시 언급하겠습니다.

**Comment by yongbin1** [comment]
넵 알겠습니다!!

**Comment by kkyh12180** [comment]
@yongbin1 3번 과정에서 지속적으로 오류가 발생합니다. 이 부분 확인 부탁드립니다.

**Comment by kkyh12180** [comment]
@yongbin1 그리고 application.yml의 경로를 명시해주시길 바랍니다.

**Comment by yongbin1** [comment]
@kkyh12180 
application.yml 부분 만드는 법을 다시 수정했습니다 확인해주세요!!

**Comment by kkyh12180** [comment]
@yongbin1 
![image](https://github.com/hackersground-kr/hackers-ground/assets/80297525/a604020d-67b5-4252-9bf5-f5913b0e80d0)
![image](https://github.com/hackersground-kr/hackers-ground/assets/80297525/347517db-ad73-4825-9b86-7504c32ca605)

에러 체크 부탁드립니다.

**Comment by kkyh12180** [comment]
@yongbin1 mysql 실행 과정에서 오류가 발생합니다. 6번에서 실행 환경을 명시해주시길 바랍니다.

**Comment by yongbin1** [comment]
6번의 mysql 실행환경을 명시해두었습니다!! 확인 부탁드립니다

**Comment by kkyh12180** [comment]
@yongbin1 mysql이 로컬에 설치되어 있어야 하나요? 만약 그렇다면 기본 준비 사항에 추가 부탁드립니다.

**Comment by yongbin1** [comment]
아 네네 mysql이 로컬에 설치되어있어야합니다.. 준비사항에 추가해놓겠습니다

**Comment by kkyh12180** [comment]
@yongbin1 
ERROR 9002 (28000): FATAL: Invalid Username specified. Please check the Username and retry connection. The Username should be in <username@hostname> format.
위의 오류와 함께 데이터베이스 연결이 되지 않습니다. 확인 부탁 드립니다.

**Comment by kkyh12180** [comment]
@yongbin1 
ERROR 9000 (HY000): Client with IP address '{{ ip 주소 }}' is not allowed to connect to this MySQL server.
추가 오류 발생했습니다. 체크 부탁 드립니다.

**Comment by yongbin1** [comment]
@kkyh12180 3번 부분 변경했습니다. 한번 확인 부탁드립니다!

**Comment by kkyh12180** [comment]
@yongbin1 
데이터베이스 접속 확인했습니다!
이후 use smonkey; 실행 시
ERROR 1049 (42000): Unknown database 'smonkey'
오류 발생합니다. 확인 부탁드립니다.

**Comment by yongbin1** [comment]
@kkyh12180 죄송합니다
use smonkey; 는 필요없는 명령어 입니다. 밑의 명령어만 수행해주시면 됩니다!!
리드미 변경했습니다

**Comment by kkyh12180** [comment]
@yongbin1 
안드로이드 앱 배포 과정에서
gh workflow run "Build and Deploy to App Center" --repo <이름>/<repo 이름>
이 작동하지 않습니다. 확인 부탁드립니다.

**Comment by kkyh12180** [comment]
Run wzieba/AppCenter-Github-Action@v1
  with:
    token: ***
    appName: YHKim/smonkey
    file: android/app/build/outputs/apk/debug/app-debug.apk
    group: Collaborators
    debug: false
  env:
    JAVA_HOME: /opt/hostedtoolcache/Java_Adopt_jdk/17.0.7-7/x64
/usr/bin/docker run --name a6c8c1dcd5[2](https://github.com/kkyh12180/smonkey/actions/runs/5348338607/jobs/9698089322#step:9:2)447aab4cf09246[3](https://github.com/kkyh12180/smonkey/actions/runs/5348338607/jobs/9698089322#step:9:3)[4](https://github.com/kkyh12180/smonkey/actions/runs/5348338607/jobs/9698089322#step:9:4)8b8833447b_ab8d98 --label 2a6c8c --workdir /github/workspace --rm -e "JAVA_HOME" -e "INPUT_TOKEN" -e "INPUT_APPNAME" -e "INPUT_FILE" -e "INPUT_GROUP" -e "INPUT_BUILDVERSION" -e "INPUT_BUILDNUMBER" -e "INPUT_RELEASENOTES" -e "INPUT_GITRELEASENOTES" -e "INPUT_NOTIFYTESTERS" -e "INPUT_DEBUG" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/smonkey/smonkey":"/github/workspace" 2a6c8c:1dcd[5](https://github.com/kkyh12180/smonkey/actions/runs/5348338607/jobs/9698089322#step:9:5)2447aab4cf0924[6](https://github.com/kkyh12180/smonkey/actions/runs/5348338607/jobs/9698089322#step:9:6)348b883344[7](https://github.com/kkyh12180/smonkey/actions/runs/5348338607/jobs/9698089322#step:9:7)b
Error: Failed to create release upload for android/app/build/outputs/apk/debug/app-debug.apk. Backend response: Not found. Correlation ID: 23147c9f-c4f0-4c[8](https://github.com/kkyh12180/smonkey/actions/runs/5348338607/jobs/9698089322#step:9:8)3-[9](https://github.com/kkyh12180/smonkey/actions/runs/5348338607/jobs/9698089322#step:9:9)5af-8e74b5f80e62

**Comment by kkyh12180** [comment]
@yongbin1 round4 제출 부탁드립니다!

**Comment by kkyh12180** [comment]
@yongbin1 아 round4가 아니라 추후 공지 확인하시고 맞게 제출해주세요!
