### ISSUE TITLE
[우아한 남매들] 해커톤 앱 제출

### ISSUE THREAD

**Issue by SeokgyuYun** [hackersground-kr/hackers-ground-2023#122]
- **팀 이름**: 우아한 남매들
- **팀 리포지토리**: https://github.com/hackersground-kr/Woowa-Siblings/tree/main

**Comment by khj1030** [comment]
@SeokgyuYun 안드로이드 과정에서 "Add new app 버튼을 누르고 App name, Release Type, Icon, OS, Platform을 선택한 후 Add new app을 클릭한다." 옵션 선택 내용까지 상세하게 기재부탁드립니다.

**Comment by khj1030** [comment]
@SeokgyuYun 안드로이드 과정 "3. 안드로이드 프로젝트로 들어가 앱 단위의 build.gradle에 아래 dependency를 추가한다." 부분 자세한 실행 경로(과정) 기재 부탁드립니다.
