### ISSUE TITLE
[cppva] 해커톤 앱 제출

### ISSUE THREAD

**Issue by seung365** [hackersground-kr/hackers-ground-2023#125]
👆👆👆 상단의 제목에 팀 이름을 반드시 적어 주세요 👆👆👆

팀 이름: cppva
팀 리포지토리: https://github.com/hackersground-kr/cppva

**Comment by geunchanKim** [comment]
@seung365 
리드미 다시 작성부탁드립니다. 제가 리드미만을 읽고 실행할 수 있어야 합니다. 처음부터 천천히 한 단계 씩 설명 적어주세요.

**Comment by seung365** [comment]
@mouse4432  
리드미 수정했습니다. 확인 부탁 드립니다.

**Comment by geunchanKim** [comment]
@seung365 
가격 책정 플랜에서 새 App Service 요금제를 만들어 줍니다.
새로 만들기 진행하는건가요?
가격 책정 플랜에서 있는 리스트 중에 어떤 것을 선택하나요?
리드미에 구체적으로 적어주시고 다시 @로 언급 해주세요!

**Comment by seung365** [comment]
@mouse4432 
가격 책정 플랜에 대해서 좀더 자세히 적어놓았습니다.
확인 부탁드립니다.

**Comment by geunchanKim** [comment]
@seung365 
그 후 리포지토리_이름/.github/workflows/ 생성된 yml파일을 연다.
현재 3개 yml 파일 있습니다. 어떤 파일을 여나요? 아니면 모든 파일을 여나요?
리드미 수정부탁드립니다!

**Comment by seung365** [comment]
@mouse4432 
yml파일 하나를 지정해 주었습니다. 확인 부탁드립니다.

**Comment by geunchanKim** [comment]
@seung365 
cppva4432 리소스 그룹 생성 해드렸으니 여기에서 한 번 처음부터 리드미 따라 진행해보시고 필요한 부분과 빌드와 디플로이 단계를 구체적으로 적어주세요.

**Comment by geunchanKim** [comment]
- name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'chan443233'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BBC44BBCA0934DEAB1F9794705188724 }}
          package: .

**Comment by geunchanKim** [comment]
@seung365 
아무것도 건드리지 않으면 yaml 파일에 이런 부분이 생기네요!! 참고해주세요!!

**Comment by seung365** [comment]
@mouse4432 
  - name: Deploy to Azure Web App
    id: deploy-to-webapp
    uses: azure/webapps-deploy@v2
    with:
      app-name: 'chan443233'
      slot-name: 'Production'
      publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BBC44BBCA0934DEAB1F9794705188724 }}
      package: .
      위에 보내주신 이코드 말씀인가요

**Comment by geunchanKim** [comment]
네네, 앱 이름과 시크릿 키는 다를겁니다!!

**Comment by geunchanKim** [comment]
매칭 존으로 와주세요!! 리드미 파일 내용 조금만 수정하면 될 거 같아요!! 실행되었어요!!

**Comment by geunchanKim** [comment]
@seung365 
커멘트 확인해주세요!

**Comment by seung365** [comment]
@mouse4432 
README 수정했습니다. 확인 부탁 드립니다.
