### ISSUE TITLE
[**Park_At**] 해커톤 앱 제출

### ISSUE THREAD

**Issue by igeon20** [hackersground-kr/hackers-ground-2023#130]
**👆👆👆 상단의 제목에 팀 이름을 반드시 적어 주세요 👆👆👆**

- **팀 이름**: {{ Park_At }}
- **팀 리포지토리**: https://github.com/hackersground-kr/park-at

**Comment by meronana** [comment]
@igeon20 내일 아침 7시까지 꼭 제출 부탁드립니다!

**Comment by meronana** [comment]
@igeon20 
![image](https://github.com/hackersground-kr/hackers-ground/assets/114082017/c487130b-3623-4564-90ac-a815e06397d9)
gradle sync가 계속 안됩니다.

**Comment by meronana** [comment]
또한 7번의 Key Store Path 부분에는 키 파일을 저장할 경로를, 위와 아래의 Password와 Confirm 모두 같은 비밀번호를 입력하고, 인증서에 영문명을 적은 후, ‘OK’를 눌러줍니다. 라고 하는데 비밀번호는 임의로 하는건지, 인증서에 영문명 또한 임의로 하는 건지 궁금합니다.

**Comment by meronana** [comment]
@igeon20 저는 이제 퇴근하는데, 6시에 다시 돌아오겠습니다. 아마 그 전 쯤 도착 할 텐 데  그 때 또 확인해 드리겠습니다.
