### ISSUE TITLE
[기요미니상] 해커톤 앱 제출

### ISSUE THREAD

**Issue by minisangmini** [hackersground-kr/hackers-ground-2023#131]
**👆👆👆 상단의 제목에 팀 이름을 반드시 적어 주세요 👆👆👆**

- **팀 이름**: 기요미니상
- **팀 리포지토리**: https://github.com/hackersground-kr/minisang

**Comment by hdddhdd** [comment]
@minisangmini 

배포 과정을 기존에 공지된 것처럼 아래 링크들을 참조하여 상세히 작성 부탁드립니다. :)

사전워크샵 전체 레포: https://github.com/hackersground-kr/workshop

애저 포털 이용하기 실습자료: https://github.com/hackersground-kr/workshop/blob/main/docs/session-01/README.md

GitHub 코드스페이스&코파일럿 실습자료: https://github.com/hackersground-kr/workshop/blob/main/docs/session-02/README.md

**Comment by hdddhdd** [comment]
https://github.com/hackersground-kr/minisang

**Comment by hdddhdd** [comment]
@minisangmini 

리드미 수정완료되시면 태그 또는 디스코드 디엠으로 알려주세요!
