### ISSUE TITLE
[파일 탐색기] 해커톤 앱 제출

### ISSUE THREAD

**Issue by wxodi0** [hackersground-kr/hackers-ground-2023#132]
**👆👆👆 상단의 제목에 팀 이름을 반드시 적어 주세요 👆👆👆**

- **팀 이름**: 파일 탐색기
- **팀 리포지토리**: [https://github.com/hackersground-kr/{{ 팀 리포지토리 }}](https://github.com/hackersground-kr/FileExplorer)

**Comment by mouse4432** [comment]
@wxodi0
리소스 그룹 생성, 웹앱 만들기 등등 다양한 옵션이 있는데요. 그 부분에 대해 구체적으로 적어주셔야 합니다. 구체적으로 적어주세요!!!

**Comment by geunchanKim** [comment]
@wxodi0 
리드미 다시 작성부탁드립니다. 제가 리드미만을 읽고 실행할 수 있어야 합니다. 처음부터 천천히 한 단계 씩 설명 적어주세요.

**Comment by geunchanKim** [comment]
@wxodi0 
리드미 작성 관련 모르겠으면 매칭존에 오세요!

**Comment by geunchanKim** [comment]
@wxodi0 
가격 책정 플랜은 어떻게 진행했나요?
리드미에 적어주시고 이슈에 comment에 @mouse4432 언급해서 알려주세요!! 그래야 바로 확인 가능합니다!
