### ISSUE TITLE
[**.기요미니상 **] 해커톤 앱 제출

### ISSUE THREAD

**Issue by minisangmini** [hackersground-kr/hackers-ground-2023#135]
**👆👆👆 상단의 제목에 팀 이름을 반드시 적어 주세요 👆👆👆**

- **팀 이름**: {{ 기요미니상 }}
- **팀 리포지토리**: https://github.com/hackersground-kr/minisang

**Comment by geunchanKim** [comment]
@minisangmini 
round3로 올린건가요? 
아니면 round4로 올리신건가요?
