### ISSUE TITLE
[cometo] 해커톤 발표자료 제출

### ISSUE THREAD

**Issue by kimgh06** [hackersground-kr/hackers-ground-2023#186]
**👆👆👆 상단의 제목에 팀 이름을 반드시 적어 주세요 👆👆👆**

- **팀 이름**: cometo
- **팀 리포지토리**: https:/
[c61191dc59a06651.pdf](https://github.com/hackersground-kr/hackers-ground/files/11841950/c61191dc59a06651.pdf)
/github.com/hackersground-kr/cometo

**Comment by dmsrud1218** [comment]
저희 readme 제품/서비스 소개부분에 9시에 올렸는데 발표자료에 띄어쓰기로 저장되어있어서 링크가 계속 걸리지 않아서 제대로 올라가지 못한거같습니다. 확인해보시고 말해주세요!
