### ISSUE TITLE
[모공이공] 해커톤 주제 제출

### ISSUE THREAD

**Issue by pathemata** [hackersground-kr/hackers-ground-2023#58]
**👆👆👆 상단의 제목에 팀 이름을 반드시 적어 주세요 👆👆👆**

- **팀 이름**: 모공이공
- **팀 리포지토리**https://github.com/hackersground-kr/mobile20

**Comment by khj1030** [comment]
@pathemata TOPIC.md에서 기존에 적혀있던 안내문("(필수) 해커톤에서 만들 제품 또는 서비스 이름을 적어주세요.")과 같은 문구는 지우고 제출해주세요.
