### ISSUE TITLE
[Byte] 해커톤 2차 주제 제출

### ISSUE THREAD

**Issue by manjookim** [hackersground-kr/hackers-ground-2023#99]
**👆👆👆 상단의 제목에 팀 이름을 반드시 적어 주세요 👆👆👆**

- **팀 이름**: Byte
- **팀 리포지토리**: https://github.com/hackersground-kr/Byte

**Comment by hackersground-events** [comment]
3일차 오전 8시에 최종 발표자료 확인할 때 함께 확인하겠습니다.
